import os
import json
import logging
import httpx
from providers.base import BaseLLMProvider
from schemas import AgentStepRequest, AgentStepResponse

logger = logging.getLogger("privacylens.ollama")

SYSTEM_PROMPT = """You are PrivacyLens Agent, an offline browser vision assistant.
All sensitive data has been REDACTED with typed placeholders: [NAME_1], [EMAIL_1], [PHONE_1], [AADHAAR_1], [PAN_1], [PASSWORD_1], [CARD_NUMBER_1].
Images have been blurred/blacked out at PII regions.
Output strictly JSON:
{
  "action": "click" | "type" | "scroll" | "select" | "wait" | "done",
  "selector": "<CSS selector>",
  "value": "<placeholder or text>",
  "direction": "up" | "down" | null,
  "reasoning": "<explanation>",
  "confidence": 0.95
}
"""


class OllamaProvider(BaseLLMProvider):
    def __init__(self, endpoint: str = None, model: str = None):
        self.endpoint = (endpoint or os.getenv("OLLAMA_ENDPOINT", "http://127.0.0.1:11434")).rstrip("/")
        self.model = model or os.getenv("OLLAMA_MODEL", "qwen2-vl")

    async def generate_action(self, request: AgentStepRequest) -> AgentStepResponse:
        dom_summary = []
        for elem in request.sanitized_dom[:60]:
            dom_summary.append(
                f"<{elem.tag}> sel='{elem.selector}' name='{elem.name or ''}' text='{elem.visible_text or ''}' placeholder='{elem.placeholder or ''}'"
            )

        prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"TASK: {request.task}\n\n"
            f"DOM ELEMENTS:\n" + "\n".join(dom_summary) + "\n\n"
            f"Provide next JSON action:"
        )

        images = []
        if request.redacted_image_base64:
            clean_b64 = request.redacted_image_base64.split(",")[-1]
            images.append(clean_b64)

        payload = {
            "model": self.model,
            "prompt": prompt,
            "format": "json",
            "stream": False,
            "images": images if images else None,
        }

        async with httpx.AsyncClient(timeout=45.0) as client:
            try:
                res = await client.post(f"{self.endpoint}/api/generate", json=payload)
                res.raise_for_status()
                data = res.json()
                parsed = json.loads(data.get("response", "{}"))

                return AgentStepResponse(
                    action=parsed.get("action", "done"),
                    selector=parsed.get("selector"),
                    value=parsed.get("value"),
                    direction=parsed.get("direction"),
                    reasoning=parsed.get("reasoning", "Generated by local Ollama vision agent."),
                    confidence=float(parsed.get("confidence", 0.85)),
                    step_number=len(request.history) + 1,
                )
            except Exception as e:
                logger.error(f"Ollama connection error: {e}. Falling back to MockProvider.")
                from providers.mock_provider import MockProvider
                return await MockProvider().generate_action(request)
